workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages: # List of stages for jobs, and their order of execution
  - lint
  - build
  - test
#  - deploy

lint-job:
  stage: lint
  script:
    - cargo fmt --check
    - cargo clippy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cargo leptos build --release 

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - cargo leptos test --release 


# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
